# Debian install
# This is the Debian package repository of Jenkins to automate installation and upgrade. To use this repository, first add the key to your system:

# wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo apt-key add -
# Then add the following entry in your /etc/apt/sources.list:
# deb https://pkg.jenkins.io/debian-stable binary/
# Update your local package index, then finally install Jenkins:

# sudo apt-get update
# sudo apt-get install jenkins
---

- name: Install Debian apt key
  #command: wget -q -O - https://pkg.jenkins.io/debian/jenkins-ci.org.key | sudo apt-key add -
  get_url:
    url: https://pkg.jenkins.io/debian/jenkins-ci.org.key
    dest: /tmp
  
- name: UPdate source cache
  command: sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'

- name: Update at -cache
  command: apt-get update

- name: Install jenkins
  command: apt-get install jenkins
