---
- hosts: web
  remote_user: automata
  become: true
  become_method: sudo
  tasks:

   - name: Send  mail
     local_action: mail
                   host='127.0.0.1'
                   subject="[Ansible] All task completed for mail_alert playback"
       	           body="HEllo, test"
                   from="cmills@opensitesolutions.com"
                   to="user@opensitesolutons.com"
