# Pass in action variable with -e optoin
# ansible-playbook playbookfile -e "action=web"
---
- hosts: "{{server}}"
  become: yes
  become_method: sudo
  user: automata
  connection: ssh
  tasks:

  roles:
    - "{{todo}}"
