Vagrant.configure("2") do |config|

config.vm.define "ansibletower" do |anst|
 anst.vm.box = "ansible/tower"
 anst.vm.hostname = "ansibletower"
 anst.vm.network "private_network", auto_config: false, ip: "172.16.1.21"
 anst.vm.network "public_network", :bridge => "wlp4s0", :ip => "192.168.1.204"
 anst.vm.network "forwarded_port", guest: 443, host: 8084
 config.vm.provider "virtualbox" do |vbox|
       vbox.name = "ansibletower"
       vbox.gui = false
 end
end


config.vm.define "mon_1" do |mon_1|
  mon_1.vm.box = "ubuntu/trusty64"
  mon_1.vm.hostname = "mon-1"
  mon_1.vm.network "public_network", :bridge => "wlp4s0", :ip => "192.168.1.205"
  mon_1.vm.network "private_network", ip: "172.16.1.5"
  mon_1.vm.network "forwarded_port", guest: 80, host: 8085
  config.vm.provider "virtualbox" do |virtza|
	virtza.memory = "1024"
 	virtza.name = "mon_1"
	virtza.gui = false
  end
end

config.vm.define "jenkins_1" do |jenk_1|
  jenk_1.vm.box = "bento/centos-6.7"
  jenk_1.vm.hostname = "jenkins-1"
  jenk_1.vm.network "public_network", :bridge => "wlp4s0", :ip => "192.168.1.206"
  jenk_1.vm.network "private_network", ip: "172.16.1.6"
  config.vm.provider "virtualbox" do |virtzb|
	virtzb.memory = "1024"
	virtzb.name = "jenkins_1"
	virtzb.gui = false
  end
end

config.vm.provision "ansible" do |ansible|
      	ansible.playbook = "../configuration/setup.yml"
      	ansible.verbose = "v"
	ansible.groups = {
		"monitor" => ["mon_1","ansibletower"],
		"cdi" => ["jenkins_1"],
		"all:children" => ["monitor","cdi"]
	}
end

end
